[env:wemos_d1_mini32]
platform = espressif32
board = wemos_d1_mini32
framework = espidf
upload_port = COM12
monitor_port = COM12
monitor_speed = 115200
upload_speed = 921600
build_flags =
    -D LOG_LOCAL_LEVEL=ESP_LOG_INFO
